name: My First Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install dependencies
      uses: npm ci

    - name: Run tests
      uses: npm test

    - name: Print a message
      run: echo "Hello, world!"